version: '3.8'

services:
  webpanel:
    build: .
    container_name: webpanel
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      - MAX_PROCESSES=20
      - ENABLE_AUTH=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: webpanel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webpanel
    restart: unless-stopped
    profiles:
      - with-nginx 